# permissions for end users to view features.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: feature-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: banana-operator
    app.kubernetes.io/part-of: banana-operator
    app.kubernetes.io/managed-by: kustomize
  name: feature-viewer-role
rules:
- apiGroups:
  - banana.mdlwr.se
  resources:
  - features
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - banana.mdlwr.se
  resources:
  - features/status
  verbs:
  - get
