---
apiVersion: banana.mdlwr.se/v1alpha1
kind: Feature
metadata:
  labels:
    app.kubernetes.io/name: banana-dex
    app.kubernetes.io/part-of: banana-controller
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/created-by: banana-controller
  name: banana-dex
  namespace: argocd
spec:
  namespace: dex
  repo: https://git.vgregion.se/kubernetes/hubble.git
  path: infrastructure-apps/dex
  revision: HEAD
  values:
  - name: clusterName
    value: hubble-dev
  - name: environment
    value: test
  - name: type
    value: clusterip
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
---
apiVersion: banana.mdlwr.se/v1alpha1
kind: Feature
metadata:
  labels:
    app.kubernetes.io/name: banana-prometheus
    app.kubernetes.io/part-of: banana-controller
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/created-by: banana-controller
  name: banana-prometheus
  namespace: argocd
spec:
  namespace: prometheus
  repo: https://charts.bitnami.com/bitnami
  name: prometheus
  revision: 0.7.0
  values:
  - name: clusterName
    value: hubble-dev
  - name: environment
    value: test
  - name: type
    value: clusterip
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true