apiVersion: banana.mdlwr.se/v1alpha1
kind: FeatureSet
metadata:
  name: featureset-sample
  namespace: infra
spec:
  valuesFile: 
  features:
   - namespace: prometheus
     repo: https://charts.bitnami.com/bitnami
     name: prometheus
     revision: 0.7.0