apiVersion: banana.mdlwr.se/v1alpha1
kind: Feature
metadata:
  labels:
    app.kubernetes.io/name: banana-prometheus
    app.kubernetes.io/part-of: banana-controller
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/created-by: banana-controller
  name: banana-prometheus
  namespace: argocd
spec:
  namespace: prometheus
  repo: https://charts.bitnami.com/bitnami
  name: prometheus
  revision: 0.7.0