apiVersion: banana.mdlwr.se/v1alpha1
kind: FeatureSet
metadata:
  labels:
    app.kubernetes.io/name: featureset
    app.kubernetes.io/instance: featureset-sample
    app.kubernetes.io/part-of: banana-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: banana-operator
  name: featureset-sample
  namespace: infra
spec:
  features:
  - name: apache
    helm:
      repo: https://charts.bitnami.com/bitnami
      chart: apache
      targetNamespace: infra
      valuesContent: |-
        service:
          type: ClusterIP
        ingress:
          enabled: true
          hostname: www.example.com
        metrics:
          enabled: true
